# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-10 05:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField()),
                ('turn_time', models.DateTimeField()),
            ],
        ),
    ]
