# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-10 07:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_auto_20160910_0637'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drawing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=b'')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.Game')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('ready', models.BooleanField(default=False)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.Game')),
            ],
        ),
        migrations.AddField(
            model_name='drawing',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.Player'),
        ),
    ]
