# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-10 21:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_game_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='drawing',
            name='caption',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='drawing',
            name='number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='started',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='secret',
            field=models.CharField(default='secret', max_length=200),
            preserve_default=False,
        ),
    ]
