# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-10 21:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_auto_20160910_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='drawing',
            name='startingPlayer',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='startingPlayer', to='server.Player'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='turnNumber',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='drawing',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player', to='server.Player'),
        ),
    ]
