# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-11 02:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0006_auto_20160910_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 11, 2, 12, 15, 720596)),
        ),
        migrations.AddField(
            model_name='player',
            name='active',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 11, 2, 12, 15, 727887)),
        ),
        migrations.AddField(
            model_name='player',
            name='leader',
            field=models.BooleanField(default=False),
        ),
    ]
