# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-11 02:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0007_auto_20160911_0212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 11, 2, 59, 54, 747994)),
        ),
        migrations.AlterField(
            model_name='player',
            name='active',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 11, 2, 59, 54, 756605)),
        ),
    ]
